yarnPath: .yarn/releases/yarn-3.0.1.cjs

# npmRegistryServer: 'https://registry.npmjs.org'
npmRegistryServer: 'https://registry.npm.taobao.org'

# If strict (the default), Yarn won't allow modules to require packages they don't explicitly list in their own dependencies. If loose, Yarn will allow access to the packages that would have been hoisted to the top-level under 1.x installs. Note that, even in loose mode, such calls are unsafe (hoisting rules aren't predictable) and should be discouraged.
# pnpMode: 'loose'

# default
# nodeLinker: "pnp"
nodeLinker: 'node-modules'

pnpEnableInlining: false
